package com.zion.admin.id;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.zion.common.entity.BaseEntity;
import com.zion.file.entity.SysFile;
import com.zion.file.entity.SysFileGroup;
import com.zion.gen.entity.GenTable;
import com.zion.gen.entity.GenTableColumn;
import com.zion.sms.entity.SmsLog;
import com.zion.system.entity.SysConfigGroup;
import com.zion.system.entity.SysLoginLog;
import com.zion.system.entity.SysOperLog;
import com.zion.system.entity.SysRoleDept;
import com.zion.system.entity.SysRoleMenu;
import com.zion.system.entity.SysUserBlacklist;
import com.zion.system.entity.SysUserPost;
import com.zion.system.entity.SysUserRole;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.lang.reflect.Field;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class AdminSnowflakeIdPolicyTest {

    private static final List<Class<?>> BACKEND_ID_ENTITIES = List.of(
            BaseEntity.class,
            SysConfigGroup.class,
            SysLoginLog.class,
            SysOperLog.class,
            SysRoleDept.class,
            SysRoleMenu.class,
            SysUserBlacklist.class,
            SysUserPost.class,
            SysUserRole.class,
            SysFile.class,
            SysFileGroup.class,
            SmsLog.class,
            GenTable.class,
            GenTableColumn.class
    );

    @Test
    void backendEntitiesUseMybatisPlusSnowflakeIds() {
        for (Class<?> entityClass : BACKEND_ID_ENTITIES) {
            TableId tableId = idField(entityClass).getAnnotation(TableId.class);

            assertThat(tableId)
                    .as("%s.id 必须声明 MyBatis-Plus 主键策略", entityClass.getSimpleName())
                    .isNotNull();
            assertThat(tableId.type())
                    .as("%s.id 必须使用 MyBatis-Plus 雪花算法", entityClass.getSimpleName())
                    .isEqualTo(IdType.ASSIGN_ID);
        }
    }

    @Test
    void generatedEntityTemplateUsesSnowflakeIds() throws IOException {
        String template = Files.readString(projectRoot().resolve(
                "zion-core/zion-gen/src/main/resources/templates/gen/java/entity.java.vm"));

        assertThat(template).contains("IdType.ASSIGN_ID");
        assertThat(template).doesNotContain("IdType.AUTO");
    }

    @Test
    void postgresqlConversionScriptDoesNotCreateIdentityIds() throws IOException {
        String script = Files.readString(projectRoot().resolve("sql/convert_to_pg.py"));

        assertThat(script).doesNotContain("GENERATED BY DEFAULT AS IDENTITY");
    }

    @Test
    void postgresqlDdlDoesNotCreateIdentityIds() throws IOException {
        String ddl = Files.readString(projectRoot().resolve("sql/zion-system-postgresql.sql"));

        assertThat(ddl).doesNotContain("GENERATED BY DEFAULT AS IDENTITY");
    }

    private static Field idField(Class<?> entityClass) {
        Class<?> currentClass = entityClass;
        while (currentClass != null) {
            try {
                return currentClass.getDeclaredField("id");
            } catch (NoSuchFieldException ignored) {
                currentClass = currentClass.getSuperclass();
            }
        }
        throw new IllegalArgumentException(entityClass.getName() + " 未声明 id 字段");
    }

    private static Path projectRoot() {
        return Path.of(System.getProperty("user.dir")).getParent().getParent();
    }
}
